services:
  # A Docker web service
  - type: web
    name: AlaxanderFilterBot
    env: python
    startCommand: python3 main.py
    buildCommand: pip3 install -U -r requirements.txt
    repo: https://github.com/Agsbotsyt/AlaxanderFilterBot # optional
    region: oregon # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    branch: Agsmods # optional (defaults to master)
    numInstances: 1 # optional (defaults to 1)
    healthCheckPath: /
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ADMINS
        sync: false
      - key: DATABASE_URI
        sync: false
      - key: BOT_PICS
        sync: false
      - key: UPDATE_CHANNEL
        sync: false
      - key: SUPPORT_CHAT
        sync: false
      - key: AUTH_USERS
        sync: false
      - key: AUTH_CHANNEL
        sync: false
      - key: CHANNELS
        sync: false
      - key: LOG_CHANNEL 
        sync: false
